import "@/layouts/styles/globals.scss";
import React from "react";
import type { Metadata } from "next";
import { ThemeProvider } from "@/layouts/Theme/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
